export const FORGOT_PASSWORD_REQUESTING = "FORGOT_PASSWORD_REQUESTING";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_ERROR = "FORGOT_PASSWORD_ERROR";
