// flow-typed signature: f715ef4eb4f03e7afd740db5d92d67d7
// flow-typed version: <<STUB>>/react-twitter-auth_v0.0.12/flow_v0.73.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-twitter-auth'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-twitter-auth' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-twitter-auth/lib/react-twitter-auth-component' {
  declare module.exports: any;
}

declare module 'react-twitter-auth/lib/react-twitter-auth-component.min' {
  declare module.exports: any;
}

declare module 'react-twitter-auth/tests/component.property.test' {
  declare module.exports: any;
}

declare module 'react-twitter-auth/tests/rendering.test' {
  declare module.exports: any;
}

declare module 'react-twitter-auth/tests/setup.test' {
  declare module.exports: any;
}

declare module 'react-twitter-auth/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-twitter-auth/lib/react-twitter-auth-component.js' {
  declare module.exports: $Exports<'react-twitter-auth/lib/react-twitter-auth-component'>;
}
declare module 'react-twitter-auth/lib/react-twitter-auth-component.min.js' {
  declare module.exports: $Exports<'react-twitter-auth/lib/react-twitter-auth-component.min'>;
}
declare module 'react-twitter-auth/tests/component.property.test.js' {
  declare module.exports: $Exports<'react-twitter-auth/tests/component.property.test'>;
}
declare module 'react-twitter-auth/tests/rendering.test.jsx' {
  declare module.exports: $Exports<'react-twitter-auth/tests/rendering.test'>;
}
declare module 'react-twitter-auth/tests/setup.test.js' {
  declare module.exports: $Exports<'react-twitter-auth/tests/setup.test'>;
}
declare module 'react-twitter-auth/webpack.config.js' {
  declare module.exports: $Exports<'react-twitter-auth/webpack.config'>;
}
