export const LOGIN_REQUESTING = "LOGIN_REQUESTING";
export const GOOGLE_LOGIN_REQUESTING = "GOOGLE_LOGIN_REQUESTING";
export const FACEBOOK_LOGIN_REQUESTING = "FACEBOOK_LOGIN_REQUESTING";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const CONFIRM_USER_EMAIL_REQUESTING = "CONFIRM_USER_EMAIL_REQUESTING";
