export const SEARCH_GOOGLE_PLACES: string = "SEARCH_GOOGLE_PLACES";
export const SEARCH_GOOGLE_PLACES_SUCCESS: string =
  "SEARCH_GOOGLE_PLACES_SUCCESS";
export const SEARCH_GOOGLE_PLACES_ERROR: string = "SEARCH_GOOGLE_PLACES_ERROR";
